### ISSUE TITLE
seen this similar package?

### ISSUE THREAD

**Issue by peter-mouland** [alansouzati/jsx-to-string#10]
https://github.com/algolia/react-element-to-jsx-string

I haven't ran it to see if it does _exactly_ the same thing but it does look _similar_ and is being used by chai-enzyme and other big projects.

**Comment by alansouzati** [comment]
At the time I developed this library I believe this was not available or did not meet my requirements.

I created a [stackoverflow question](http://stackoverflow.com/questions/33836016/reactjs-jsx-tostring), waited a little bit, as I did get any answer and could not find anything with support to `ignoreProps` I decided to publish this.
