### ISSUE TITLE
Can't handle null-value properties

### ISSUE THREAD

**Issue by awalkerca** [alansouzati/jsx-to-string#13]
`Cannot convert undefined or null to object` is thrown when a property value is `null`. 

It appears to handle undefined, but if the property is explicitly set to `null` (which might be a valid input to a component), the parser can't handle it.

**Comment by alansouzati** [comment]
Fixed by https://github.com/alansouzati/jsx-to-string/commit/d0e466de6aea53a236cdaf1db3b5f71bc82c4a88. `jsx-to-string` version `0.2.16` released.
