### ISSUE TITLE
Object.assign isn't available in IE11

### ISSUE THREAD

**Issue by ericsoderberghp** [alansouzati/jsx-to-string#2]
IE11 doesn't support Object.assign.

![screen shot 2016-02-02 at 1 20 45 pm](https://cloud.githubusercontent.com/assets/11637956/12764640/d8de68c0-c9af-11e5-8422-be3fa32d0408.png)

**Comment by alansouzati** [comment]
Thanks fixed in https://github.com/alansouzati/jsx-to-string/commit/78ce95667ed0c0480b59c21de267dde55a35c4c2
