### ISSUE TITLE
Usage example not working

### ISSUE THREAD

**Issue by PedroFonseca** [alansouzati/jsx-to-string#3]
Hi,

I am trying out your example but it doesn't seem to be working... 
Was there any breaking changes?
Here is my test that is somewhat the same as what you have in the usages section:
https://tonicdev.com/56e973931f9bd21200fa38b6/56e973931f9bd21200fa38b7

Thanks for the help.

**Comment by PedroFonseca** [comment]
By the way, if i specify the display name it works:
https://tonicdev.com/56e973931f9bd21200fa38b6/56e973931f9bd21200fa38b7

The thing is... is there no way to get the component name automatically?

**Comment by alansouzati** [comment]
Hi thanks for reporting this. I can't see your first example anymore. Can you paste here again?

**Comment by alansouzati** [comment]
Well, I've tried locally and I could not reproduce this issue.

```
import React from 'react';
import jsxToString from 'jsx-to-string';
// or var jsxToString = require('jsx-to-string');

let Basic = React.createClass({
  render() {
    return (
      <div />
    );
  }
}); //this is your react component

console.log(jsxToString(<Basic test1="test" />)); //outputs: <Basic test1="test" />
```

Please make sure to call jsxToString function even if you are not sending any options.

`console.log(jsxToString(<Basic test1="test" />)); //outputs: <Basic test1="test" />`

**Comment by peter-mouland** [comment]
I can confirm that latest version work for me!

This is my code @PedroFonseca :

**Comment by PedroFonseca** [comment]
Hi guys,
I am now using typescript so i guess i can't use this anymore...
But still i gave it another try and i still can't get it to work...
Can you open this link?
https://tonicdev.com/pmfonseca/jsx-to-string

Anyway, the code i am using is this:
let React = require("react")
let jsxToString = require("jsx-to-string")
let Basic = React.createClass({
  render() { return ( <div>test</div> );  }
});
console.log('first example: ' + jsxToString(<Basic test1='asd'/>));
console.log('second example: ' + jsxToString(<Basic test1='asd' />, {displayName: 'Basic'}));

And my output is this:
"first example: <function (props, co…tialState;\n } test1=\"asd\" />"
"second example: <Basic test1=\"asd\" />"

**Comment by alansouzati** [comment]
I guess the issue here is mixing es6 and es5 syntax.

Can you try?

```javascript
var React = require("react")
var jsxToString = require("jsx-to-string")
var Basic = React.createClass({
  render() { return ( <div>test</div> ); }
});
console.log('first example: ' + jsxToString(<Basic test1='asd'/>));
console.log('second example: ' + jsxToString(<Basic test1='asd' />, {displayName: 'Basic'}));
```

or

```javascript
import React from "react"
import jsxToString from "jsx-to-string"
const Basic = () => <div>test</div>;

Basic.displayName = 'Basic';

console.log('first example: ' + jsxToString(<Basic test1='asd'/>));
console.log('second example: ' + jsxToString(<Basic test1='asd' />, {displayName: 'Basic'}));
```

or

```javascript
var React = require("react")
var jsxToString = require("jsx-to-string")
var Basic = React.createClass({
  displayName: 'Basic',
  render() { return ( <div>test</div> ); }
});
console.log('first example: ' + jsxToString(<Basic test1='asd'/>));
console.log('second example: ' + jsxToString(<Basic test1='asd' />, {displayName: 'Basic'}));
```

**Comment by PedroFonseca** [comment]
yes it works if you supply the displayName.
By the way, any plans on adding support for typescript?

**Comment by alansouzati** [comment]
Is typescript JSX ? can you provide an example of your JSX typescript component?

**Comment by PedroFonseca** [comment]
Typescript has a new file extension TSX and the syntax is pretty close. However, it uses a different loader than JSX... For JSX you use something like babel, for tsx you use something like ts-loader to convert your tsx into es5 javascript.

A Statefull component would be something like this
export default class PageWrapper extends React.Component<IPageWrapper, IPageWrapperState> {
    constructor(props) {
        super(props);

        this.state = {
           ...
        };
    }
    
    render() {
      return (<div>test</div>);
    }
}

And stateless component can be as simple as 
export default (props: IPageWrapper) => {
  return (<div>test</div>);
}

**Comment by alansouzati** [comment]
I would see this as a separate project, maybe `tsx-to-string` ?. feel free to fork this repo if you feel like nailing that one.
