### ISSUE TITLE
className outputs className, not class

### ISSUE THREAD

**Issue by TheSharpieOne** [alansouzati/jsx-to-string#7]
Not sure if the whole className => class thing is just React's jsx or not... but if it is not, then this library should work that way.

**Comment by alansouzati** [comment]
Sorry about the delay to get back to you. The idea behind the library is to parse a React component to its almost exact string representation. So, `className` is expected to be like that.

**Comment by TheSharpieOne** [comment]
React does className to class, this library doesn't or at least didn't work that way for me.

**Comment by alansouzati** [comment]
The idea for this library to if you have a component object like this:

`<Component className="test" />`

The string representation of that is expected to be:

`"<Component className="test" />"`

not

`"<Component class="test" />`

Let me know if this is not working. Or provide an example to illustrate your issue. Feel free to re-open.

**Comment by TheSharpieOne** [comment]
Gotcha, thanks for the clarification, sorry for the confusion.

**Comment by aaronik** [comment]
I disagree with this ticket being closed. In TypeScript, when assigning the property `class` to a jsx element (for example, `<div class="container">` a type error is thrown. JSX supports the `className` attribute, not `class`. This library not supporting `className` in the same way is an enormous usability issue. For me, my markup needs to look something like this:

```ts
return jsxToString(
    // @ts-ignore // https://github.com/grommet/jsx-to-string/issues/7
    <div class='timeline-tooltip'>
      <span>{strings('startDate')}</span>
      // @ts-ignore 
      <strong class='float-right'>{formatDate(item.start)}</strong>
      <br/><hr/>
      <span>{strings('end')}</span>
      // @ts-ignore
      <strong class='float-right'>{item.end && formatDate(item.end)}</strong>
      <br/><hr/>
      // @ts-ignore
      <strong class='float-right'>{item.content}</strong>
    </div>
  )
```

The `// @ts-ignore` directives are a pain. If your library really supports `jsx`, I think it should make this translation.
